### ISSUE TITLE
logger threshold per logger

### ISSUE THREAD

**Issue by dselivanov** [s-fleck/lgr#19]
Sorry, may be I'm missing something again, but I think it will be beneficial to be able to specify per logger thresholds. Now it seems root logger amend individual loggers threshold.

Reproduce:
```r
# remotes::install_github('dselivanov/rsparse')
library(rsparse)
logger = lgr::get_logger('rsparse')
x = matrix(rnorm(100 * 100))
res = soft_svd(x, 10)
```

Works (reduce verbosity):
```r
logger$set_threshold('warn')
res = soft_svd(x, 10)
```

Doesn't work (doesn't increase verbosity):
```r
logger$set_threshold('trace')
res = soft_svd(x, 10)
```

**Comment by s-fleck** [comment]
np the documentation of lgr is still pretty funky and i'm compiling a FAQ right now, so all the questions are helping. I am also still trying to figure out the most intutive defaults for the root logger, and I think that is exactly where your problem comes from:

Loggers have thresholds, and so do Appenders.
If you just look at the logger,
```
print(lgr::get_logger('rsparse'))

# <Logger> [all] rsparse
#
#  inherited appenders:
#    console: <AppenderConsole> [info] -> console
#    memory : <AppenderDt>      [ all] -> in memory data.table
```
you should see what is happening.

Your logger inherits the Appenders of the root logger, but the threshold of the console Appender of the root logger is just `INFO`. So when you set the threshold of `rsparse` to TRACE it gets sent to the logger, but the logger the console Appender does not process it. 

This solves your problem:
```
lgr::lgr$appenders$console$set_threshold("all") 
# because thats a bit annoying to type, theres' a shortcut for that also:
lgr::console_threshold("all")
```
In addition you might have noticed the root logger also has a second Appender calle "memory" that has a threshold of "all" by default (only if you have the data.table package installed). That one saves all log events in memory and you can access them with

```
lgr::lgr$appenders$memory$show()
# again there is a shortcut
lgr::show_log()
```

I understand this might be confusing, and in future version the default thresholds for the root logger and it's appender might change (but the underlying mechanic will stay the same)
