### ISSUE TITLE
String representation of data.frame for different logging destinations

### ISSUE THREAD

**Issue by instantkaffee** [s-fleck/lgr#71]
Logging of a data.frame to console via string_repr() is very nice feature.

Example: 
```
> lg$debug("Parameter", x= mtcars)
DEBUG [14:49:13.651] Parameter {x: <data.frame 32x11>}
```

Unfortunately when using `AppenderFile` to write to a plain textfile, the whole data-frame gets logged which for larger use-cases will create too large log files.

How can I make the behavior consistent ?

**Comment by s-fleck** [comment]
`lg$debug("Parameter", x = lgr::string_repr(mtcars))`

By default the whole `data.frame` is logged because there are some log destination where you might really want to store the full data. The `string_repr()` function generates short text representations of complex objects. console logger uses it internally by default, but for other loggers i did not want to force this.
